name: To avoid sending pull request for relating UTs when under app directory changes

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-diff-app:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch remote main branch
      run: |
        git fetch --all
        git fetch origin main

    - name: Check for branch name with regex
      id: check_branch
      run: |
        if [[ "${{ github.head_ref }}" =~ ^feature/LETRO-[0-9]+$ ]]; then
          echo "target_branch=true" >> $GITHUB_ENV
        else
          echo "target_branch=false" >> $GITHUB_ENV
        fi

    - name: Check for changes in app directory
      id: check_changes
      run: |
        if [[ "${{ env.target_branch }}" == "true" ]]; then
          if git diff --name-only origin/main...${{ github.sha }} | grep '^app/'; then
            echo "changes_in_app=true" >> $GITHUB_ENV
          else
            echo "changes_in_app=false" >> $GITHUB_ENV
          fi
        else
          echo "changes_in_app=false" >> $GITHUB_ENV
        fi

    - name: Fail if changes found in app directory
      if: env.changes_in_app == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pr_number=${{ github.event.pull_request.number }};
        curl -s -H "Authorization: token $GITHUB_TOKEN" \
             -X POST \
             -d "{\"body\":\"Close this pull request due to change under app directory.\", \"state\":\"closed\"}" \
             "https://api.github.com/repos/${{ github.repository }}/issues/${pr_number}"
