name: Avoid sending pull request for changes under app directory

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  check-diff-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch remote main branch
      run: |
        git fetch origin main

    - name: Check for branch name with regex
      id: check_branch
      run: |
        if [[ "${{ github.event.pull_request.head.ref }}" =~ ^feature/LETRO_[0-9]+.*$ ]]; then
          echo "target_branch=true" >> $GITHUB_ENV
        else
          echo "target_branch=false" >> $GITHUB_ENV
        fi

    - name: Check for changes in app directory
      id: check_changes
      run: |
        if [[ "${{ env.target_branch }}" == "true" ]]; then
          git diff --name-only origin/main...${{ github.event.pull_request.head.sha }}
          if git diff --name-only origin/main...${{ github.event.pull_request.head.sha }} | grep '^app/'; then
            echo "changes_in_app=true" >> $GITHUB_ENV
          else
            echo "changes_in_app=false" >> $GITHUB_ENV
          fi
        else
          echo "changes_in_app=false" >> $GITHUB_ENV
        fi

    - name: Fail if changes found in app directory
      if: env.changes_in_app == 'true'
      env:
        CUSTOM_GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
      run: |
        pr_number=${{ github.event.pull_request.number }};
        curl -s -H "Authorization: token $CUSTOM_GITHUB_TOKEN" \
             -X PATCH \
             -d "{\"body\":\"Closed this pull request due to detect change(s) under app directory.\", \"state\":\"closed\"}" \
             "https://api.github.com/repos/${{ github.repository }}/issues/${pr_number}"

    - name: Record closing the pull request
      if: env.changes_in_app == 'true'
      run: |
        echo "This pull request is closed: ${{ github.event.pull_request.number }}"
